[colors.primary]
background = "0x272c35"
foreground = "0xaab2c0"

[colors.normal]
black   = "0x1e2127"
red     = "0xe06c75"
green   = "0x98c379"
yellow  = "0xd19a66"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0x828791"

[colors.bright]
black   = "0x5c6370"
red     = "0xf88189"
green   = "0xb2de92"
yellow  = "0xebb27d"
blue    = "0x79c5ff"
magenta = "0xe393fa"
cyan    = "0x79d8e4"
white   = "0xe6efff"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNerdFontMono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontMono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"
